# fly.toml app configuration file generated for staketomake on 2024-09-21T16:28:02+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'staketomake'
primary_region = 'sin'

[build]

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
